name: firebase-deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'

    - name: Build frontend
      run: |
        cd frontend
        npm i
        npm run build
        
    - name: Build functions
      run: |
        cd functions
        npm i
        npm run build
        
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
